# Jekyll Configuration File

title: project-slideshow
author: alantbarlow
description: A slideshow to showcase my projects.

# Server
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname

# Output
permalink: "/:title"
keep_files: [reveal.js]
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "vendor",
  "LICENSE",
  "README.md",
]
