version: "3.9"

services:
  app:
    build: .
    stdin_open: true
    volumes:
      - type: volume
        source: project-slideshow-dev-environment
        target: /usr/src/app/

volumes:
  project-slideshow-dev-environment:
