version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app/
    stdin_open: true



