version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - type: volume
        source: project-slideshow-development
        target: /usr/src/app/
    stdin_open: true
    tty: true

volumes:
  project-slideshow-development:
