version: "3.9"

services:
  app:
    build: .
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - type: volume
        source: project-slideshow-development
        target: /usr/src/app/

volumes:
  project-slideshow-development:
